"""
Builds downloadable report artifacts (Markdown + PDF) from a completed
pipeline result. Kept separate from ui/app.py so the report format can
evolve independently of the live display layout.
"""
from datetime import datetime
from fpdf import FPDF


def _sanitize_pdf_text(text) -> str:
    """
    fpdf2's built-in core fonts (Helvetica etc.) only support the Latin-1
    character set, not full Unicode — so em-dashes, curly quotes, and
    similar characters that Gemini's output regularly includes will crash
    PDF generation. Rather than bundling a full Unicode font just to
    support a handful of punctuation marks, we normalize those characters
    to their plain-ASCII equivalents before they reach the PDF.
    """
    if not isinstance(text, str):
        return text
    replacements = {
        "\u2014": "-",   # em dash —
        "\u2013": "-",   # en dash –
        "\u2018": "'",   # left single quote '
        "\u2019": "'",   # right single quote '
        "\u201c": '"',   # left double quote "
        "\u201d": '"',   # right double quote "
        "\u2026": "...", # ellipsis …
        "\u2022": "-",   # bullet •
        "\u2192": "->",  # right arrow →
        "\u2260": "!=",  # not equal ≠
        "\u00d7": "x",   # multiplication sign ×
    }
    for uni_char, ascii_equiv in replacements.items():
        text = text.replace(uni_char, ascii_equiv)
    # Final safety net: strip anything still outside Latin-1 rather than
    # letting a stray character crash the whole PDF export.
    return text.encode("latin-1", errors="replace").decode("latin-1")


def build_markdown_report(company_name: str, ticker: str, result: dict) -> str:
    brief = result.get("brief", {})
    forecast = result.get("forecast_output", {})
    risk = result.get("risk_output", {})
    comp = result.get("competitor_summary", {})

    lines = [
        f"# Due-Diligence Brief: {company_name} ({ticker})",
        f"*Generated {datetime.now().strftime('%d %B %Y')} — AI Due-Diligence Agent*",
        "",
        f"## {brief.get('headline', '')}",
        "",
        "## Financial Summary",
        brief.get("financial_summary", ""),
        "",
        "## Forecast Analysis",
        brief.get("forecast_analysis", ""),
        "",
        "## Valuation",
        brief.get("valuation_analysis", ""),
        "",
        "## Competitive Position",
        brief.get("competitive_position", ""),
        "",
        "## Key Risks",
    ]
    for r in brief.get("key_risks", []):
        lines.append(f"- {r}")
    lines += [
        "",
        "## Recommendation",
        brief.get("recommendation", ""),
        "",
        f"**Limitations:** {brief.get('limitations', '')}",
        "",
        "---",
        "## Appendix: Forecast Detail",
    ]
    for metric, fdata in forecast.items():
        cagr = fdata.get("cagr_pct")
        lines.append(f"**{metric.replace('_', ' ').title()}** — CAGR: "
                      f"{f'{cagr:+.1f}%' if cagr is not None else 'n/a'}, "
                      f"Confidence: {fdata.get('confidence', 'n/a')}")
    lines += [
        "",
        "## Appendix: Risk Flags",
    ]
    for flag in risk.get("risk_flags", []):
        lines.append(f"- **{flag.get('flag', '')}** ({flag.get('severity', '')}): {flag.get('evidence', '')}")

    lines += [
        "",
        "---",
        "*This report was generated by an AI multi-agent pipeline (SEC EDGAR + Gemini) "
        "for portfolio/demonstration purposes. It is a first-draft research aid, not "
        "verified investment advice — see limitations above.*",
    ]
    return "\n".join(lines)


class _ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(20, 20, 20)
        self.cell(0, 10, _sanitize_pdf_text(self.title_text), ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, _sanitize_pdf_text(self.subtitle_text), ln=True)
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def section(self, heading: str, body: str):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(180, 130, 40)
        self.cell(0, 8, _sanitize_pdf_text(heading.upper()), ln=True)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 5.5, _sanitize_pdf_text(body))
        self.ln(3)


def build_pdf_report(company_name: str, ticker: str, result: dict) -> bytes:
    brief = result.get("brief", {})
    forecast = result.get("forecast_output", {})
    risk = result.get("risk_output", {})

    pdf = _ReportPDF()
    pdf.title_text = f"Due-Diligence Brief: {company_name} ({ticker})"
    pdf.subtitle_text = f"Generated {datetime.now().strftime('%d %B %Y')} - AI Due-Diligence Agent"
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 6, _sanitize_pdf_text(brief.get("headline", "")))
    pdf.ln(3)

    pdf.section("Financial Summary", brief.get("financial_summary", ""))
    pdf.section("Forecast Analysis", brief.get("forecast_analysis", ""))
    pdf.section("Valuation", brief.get("valuation_analysis", ""))
    pdf.section("Competitive Position", brief.get("competitive_position", ""))

    risks_text = "\n".join(f"- {r}" for r in brief.get("key_risks", []))
    pdf.section("Key Risks", risks_text or "None flagged.")

    pdf.section("Recommendation", brief.get("recommendation", ""))
    pdf.section("Limitations", brief.get("limitations", ""))

    forecast_lines = []
    for metric, fdata in forecast.items():
        cagr = fdata.get("cagr_pct")
        forecast_lines.append(
            f"{metric.replace('_', ' ').title()}: CAGR "
            f"{f'{cagr:+.1f}%' if cagr is not None else 'n/a'}, "
            f"confidence: {fdata.get('confidence', 'n/a')}"
        )
    pdf.section("Appendix: Forecast Detail", "\n".join(forecast_lines) or "No forecast data.")

    flag_lines = [
        f"{f.get('flag', '')} ({f.get('severity', '')}): {f.get('evidence', '')}"
        for f in risk.get("risk_flags", [])
    ]
    pdf.section("Appendix: Risk Flags", "\n".join(flag_lines) or "No flags raised.")

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(
        0, 5,
        "This report was generated by an AI multi-agent pipeline (SEC EDGAR + Gemini) "
        "for portfolio/demonstration purposes. It is a first-draft research aid, not "
        "verified investment advice."
    )

    return bytes(pdf.output())
